name: Feature Request
description: Suggest a new feature or enhancement
title: "[Feature]: "
labels: ["enhancement"]
body:
  - type: markdown
    attributes:
      value: |
        Thanks for suggesting a feature! Please describe what you'd like to see in Portal.

  - type: checkboxes
    id: prerequisites
    attributes:
      label: Prerequisites
      options:
        - label: I have searched existing issues/discussions to ensure this hasn't been requested
          required: true

  - type: textarea
    id: problem
    attributes:
      label: Problem Statement
      description: What problem does this feature solve? What's the use case?
      placeholder: |
        I'm trying to create a transition that...
        Currently I have to work around this by...
    validations:
      required: true

  - type: textarea
    id: solution
    attributes:
      label: Proposed Solution
      description: How would you like this to work?
      placeholder: |
        I'd like a modifier like `.portalTransition(...)` that...
    validations:
      required: true

  - type: textarea
    id: api
    attributes:
      label: API Sketch
      description: If you have ideas for the API, sketch it out
      render: swift
      placeholder: |
        // Example usage
        view.portalTransition(
            id: "item",
            animation: .spring,
            newParameter: .value
        ) {
            LayerView()
        }

  - type: textarea
    id: alternatives
    attributes:
      label: Alternatives Considered
      description: What alternatives have you considered? Why wouldn't they work?

  - type: dropdown
    id: breaking
    attributes:
      label: Breaking Change?
      description: Would this require breaking changes to existing API?
      options:
        - "No"
        - "Yes - minor adjustment"
        - "Yes - significant migration"
        - "Not sure"

  - type: textarea
    id: additional
    attributes:
      label: Additional Context
      description: Any other context, screenshots, or examples
