# .github/workflows/swift.yml
name: Swift CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      matrix:
        swift-version: ['5.9', '6.0'] 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Swift ${{ matrix.swift-version }}
        uses: swift-actions/setup-swift@v2.3.0 
        with:
          swift-version: ${{ matrix.swift-version }}

      - name: Build
        run: swift build

      - name: Run tests
        run: swift test
