# .github/workflows/swift.yml
name: Swift CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        swift-version: ['6.0'] 
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Setup Swift ${{ matrix.swift-version }}
        uses: swift-actions/setup-swift@latest
        with:
          swift-version: ${{ matrix.swift-version }}

      - name: Build (iOS Debug)
        run: |
          xcodebuild -toolchain swift -scheme Portal -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' build

      - name: Test (iOS Debug)
        run: |
          xcodebuild -toolchain swift -scheme Portal -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' test

      - name: Build (iOS Release)
        run: |
          xcodebuild -toolchain swift -scheme Portal -configuration Release -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' build

      - name: Test (iOS Release)
        run: |
          xcodebuild -toolchain swift -scheme Portal -configuration Release -destination 'platform=iOS Simulator,name=iPhone 15,OS=latest' test
