name: Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    name: Run Tests
    runs-on: macos-15

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Show Xcode version
      run: xcodebuild -version

    - name: Find latest iOS simulator
      id: find-sim
      run: |
        # Get the latest iOS runtime version
        LATEST_IOS=$(xcrun simctl list runtimes | grep "iOS" | tail -1 | sed -E 's/.*iOS ([0-9]+\.[0-9]+).*/\1/')
        echo "Latest iOS version: $LATEST_IOS"
        echo "ios_version=$LATEST_IOS" >> $GITHUB_OUTPUT

    - name: Run all tests
      run: |
        set -o pipefail
        xcodebuild test \
          -scheme Portal-Package \
          -destination "platform=iOS Simulator,OS=${{ steps.find-sim.outputs.ios_version }}" \
          -enableCodeCoverage YES \
          CODE_SIGN_IDENTITY="" \
          CODE_SIGNING_REQUIRED=NO

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results-${{ matrix.scheme }}
        path: TestResults-${{ matrix.scheme }}.xcresult
        retention-days: 30
