name: Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test:
    name: Run Tests
    runs-on: macos-15

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        submodules: recursive

    - name: Show Xcode version
      run: xcodebuild -version

    - name: Run all tests
      run: |
        set -o pipefail
        swift test \
          --parallel \
          --enable-code-coverage

    - name: Upload test results
      if: always()
      uses: actions/upload-artifact@v4
      with:
        name: test-results-${{ matrix.scheme }}
        path: TestResults-${{ matrix.scheme }}.xcresult
        retention-days: 30
